Repository quintoandar/butterfree, pull requests merged in 2020-07, with the labels that each got.

#199 [MLOP-415] GitHub Actions CI
  .github/workflows/publish.yml
  .github/workflows/test.yml
  Makefile
  butterfree/transform/transformations/h3_transform.py
  check_version.sh
  publish.sh
  requirements.dev.txt
  requirements.lint.txt
  setup.py
Labels: enhancement, feature

#201 [MLOP-418] Take Butterfree's docs to the master branch
  .gitignore
  GITFLOW.md
  Makefile
  docs/Makefile
  docs/index.html
  docs/make.bat
  docs/source/butterfree.clients.rst
  docs/source/butterfree.configs.db.rst
  docs/source/butterfree.configs.rst
  docs/source/butterfree.constants.rst
  docs/source/butterfree.dataframe_service.rst
  docs/source/butterfree.extract.pre_processing.rst
  docs/source/butterfree.extract.readers.rst
  docs/source/butterfree.extract.rst
  docs/source/butterfree.load.rst
  docs/source/butterfree.load.writers.rst
  docs/source/butterfree.pipelines.rst
  docs/source/butterfree.reports.rst
  docs/source/butterfree.rst
  docs/source/butterfree.testing.dataframe.rst
  docs/source/butterfree.testing.rst
  docs/source/butterfree.transform.features.rst
  docs/source/butterfree.transform.rst
  docs/source/butterfree.transform.transformations.rst
  docs/source/butterfree.transform.transformations.user_defined_functions.rst
  docs/source/butterfree.transform.utils.rst
  docs/source/butterfree.validations.rst
  docs/source/conf.py
  docs/source/configuration.md
  docs/source/extract.md
  docs/source/getstart.md
  docs/source/home.md
  docs/source/index.rst
  docs/source/load.md
  docs/source/modules.rst
  docs/source/stream.md
  docs/source/transform.md
  requirements.dev.txt
  requirements.txt
  setup.py
Labels: documentation

#204 Fix H3 import
  butterfree/transform/transformations/__init__.py
  tests/integration/butterfree/transform/test_aggregated_feature_set.py
  tests/unit/butterfree/transform/transformations/test_h3_transform.py
Labels: bug

#205 Update notebooks examples
  examples/aggregated_feature_set/aggregated_feature_set.ipynb
  examples/simple_feature_set/simple_feature_set.ipynb
  examples/spark_function_and_window/spark_function_and_window.ipynb
  examples/streaming_feature_set/events/20582255.json
  examples/streaming_feature_set/events/32922718.json
  examples/streaming_feature_set/events/32924720.json
  examples/streaming_feature_set/events/32926721.json
  examples/streaming_feature_set/events/32928722.json
  examples/streaming_feature_set/events/32930724.json
  examples/streaming_feature_set/events/32932727.json
  examples/streaming_feature_set/events/32934729.json
  examples/streaming_feature_set/events/32936731.json
  examples/streaming_feature_set/events/32938733.json
  examples/streaming_feature_set/events/32940736.json
  examples/streaming_feature_set/events/32942738.json
  examples/streaming_feature_set/events/32944741.json
  examples/streaming_feature_set/events/32946743.json
  examples/streaming_feature_set/events/32948745.json
  examples/streaming_feature_set/events/32950747.json
  examples/streaming_feature_set/events/32952749.json
  examples/streaming_feature_set/events/32954751.json
  examples/streaming_feature_set/events/32956753.json
  examples/streaming_feature_set/events/32958755.json
  examples/streaming_feature_set/streaming_feature_set.ipynb
Labels: bug

#206 Fixing an attribute reference error
  butterfree/transform/transformations/aggregated_transform.py
  tests/unit/butterfree/transform/transformations/test_aggregated_transform.py
Labels: bug

#207 Fix schema and reports.
  butterfree/reports/metadata.py
  butterfree/transform/feature_set.py
Labels: bug

#211 [MLOP-417] Remove Drone yml/Drone references
  .drone.yml
Labels: enhancement

#208 Fix reports
  butterfree/reports/metadata.py
  butterfree/transform/feature_set.py
Labels: bug

#214 Release 1.0.1
  CHANGELOG.md
  setup.py
Labels: release
