Repository quintoandar/butterfree, pull requests merged in 2020-11, with the labels that each got.

#251 [MLOP-534] Enable interval and full writing on writers
  .gitignore
  butterfree/load/writers/historical_feature_store_writer.py
  butterfree/load/writers/online_feature_store_writer.py
  butterfree/load/writers/writer.py
  tests/integration/butterfree/load/test_sink.py
  tests/integration/butterfree/pipelines/test_feature_set_pipeline.py
  tests/unit/butterfree/load/writers/test_historical_feature_store_writer.py
Labels: feature

#255 [MLOP-540] Update Docstrings on OnlineFeatureStoreWriter regarding using end_date parameter
  butterfree/load/writers/online_feature_store_writer.py
Labels: documentation

#254 [MLOP-538] Slice df between start_date and end_date at the output of the FeatureSet
  butterfree/transform/aggregated_feature_set.py
  butterfree/transform/feature_set.py
  tests/integration/butterfree/transform/conftest.py
  tests/integration/butterfree/transform/test_feature_set.py
Labels: feature

#252 [MLOP-535] Enable check schema on writer
  butterfree/clients/cassandra_client.py
  butterfree/clients/spark_client.py
  butterfree/load/writers/historical_feature_store_writer.py
  butterfree/load/writers/online_feature_store_writer.py
  butterfree/load/writers/writer.py
  tests/integration/butterfree/load/test_sink.py
  tests/integration/butterfree/pipelines/conftest.py
  tests/integration/butterfree/pipelines/test_feature_set_pipeline.py
  tests/unit/butterfree/clients/conftest.py
  tests/unit/butterfree/clients/test_cassandra_client.py
  tests/unit/butterfree/hooks/schema_compatibility/test_cassandra_table_schema_compatibility_hook.py
  tests/unit/butterfree/load/test_sink.py
  tests/unit/butterfree/load/writers/test_historical_feature_store_writer.py
  tests/unit/butterfree/load/writers/test_online_feature_store_writer.py
Labels: enhancement

#253 [MLOP-537] Refactor pipeline run interface
  butterfree/pipelines/feature_set_pipeline.py
Labels: feature

#256 [MLOP-539] Fix validate on HistoricalFeatureStore for interval writing
  butterfree/clients/spark_client.py
  butterfree/configs/db/s3_config.py
  butterfree/extract/readers/file_reader.py
  butterfree/load/writers/historical_feature_store_writer.py
  tests/integration/butterfree/load/test_sink.py
  tests/integration/butterfree/pipelines/test_feature_set_pipeline.py
  tests/unit/butterfree/clients/test_spark_client.py
  tests/unit/butterfree/extract/readers/test_file_reader.py
  tests/unit/butterfree/load/writers/test_historical_feature_store_writer.py
  tests/unit/butterfree/pipelines/conftest.py
  tests/unit/butterfree/pipelines/test_feature_set_pipeline.py
  tests/unit/butterfree/transform/conftest.py
  tests/unit/butterfree/transform/test_aggregated_feature_set.py
  tests/unit/butterfree/transform/test_feature_set.py
Labels: feature

#257 Update README
  README.md
Labels: documentation

#248 [MLOP-484] Epic Incremental Feature Integration Tests
  butterfree/hooks/hookable_component.py
  tests/integration/butterfree/pipelines/conftest.py
  tests/integration/butterfree/pipelines/test_feature_set_pipeline.py
Labels: feature

#258 [MLOP-563] Enable Butterfree to write to Kafka
  butterfree/configs/db/__init__.py
  butterfree/configs/db/abstract_config.py
  butterfree/configs/db/kafka_config.py
  butterfree/load/processing/__init__.py
  butterfree/load/processing/json_transform.py
  butterfree/load/writers/historical_feature_store_writer.py
  butterfree/load/writers/online_feature_store_writer.py
  butterfree/load/writers/writer.py
  tests/unit/butterfree/configs/db/conftest.py
  tests/unit/butterfree/configs/db/test_kafka_config.py
  tests/unit/butterfree/load/conftest.py
  tests/unit/butterfree/load/processing/__init__.py
  tests/unit/butterfree/load/processing/conftest.py
  tests/unit/butterfree/load/processing/test_json_transform.py
  tests/unit/butterfree/load/writers/test_historical_feature_store_writer.py
  tests/unit/butterfree/load/writers/test_online_feature_store_writer.py
Labels: feature

#260 Fix unit-test message about black
  Makefile
Labels: documentation

#259 [MLOP-485] Create an example notebook showing the incremental feature
  butterfree/load/writers/historical_feature_store_writer.py
  butterfree/load/writers/online_feature_store_writer.py
  butterfree/transform/aggregated_feature_set.py
  examples/interval_runs/interval_runs.ipynb
  tests/integration/butterfree/pipelines/test_feature_set_pipeline.py
  tests/unit/butterfree/load/writers/test_historical_feature_store_writer.py
Labels: bug, documentation, help wanted

#261 Release 1.1.0
  CHANGELOG.md
  docs/source/butterfree.configs.db.rst
  docs/source/butterfree.load.processing.rst
  docs/source/butterfree.load.rst
  docs/source/configuration.md
  setup.py
Labels: release

#262 Fix Butterfree's workflow
  .github/workflows/publish.yml
Labels: bug

#264 Revert "Release 1.1.0"
  CHANGELOG.md
  docs/source/butterfree.configs.db.rst
  docs/source/butterfree.load.processing.rst
  docs/source/butterfree.load.rst
  docs/source/configuration.md
  setup.py
Labels: bug

#265 Release 1.1.0
  CHANGELOG.md
  docs/source/butterfree.configs.db.rst
  docs/source/butterfree.load.processing.rst
  docs/source/butterfree.load.rst
  docs/source/configuration.md
  setup.py
Labels: release

#266 [MLOP-590] Adapt KafkaConfig to receive a custom topic name
  butterfree/configs/db/kafka_config.py
  butterfree/load/writers/online_feature_store_writer.py
  tests/unit/butterfree/configs/db/test_kafka_config.py
  tests/unit/butterfree/load/writers/test_online_feature_store_writer.py
Labels: enhancement

#268 Release 1.1.1
  CHANGELOG.md
  docs/source/configuration.md
  setup.py
Labels: release
