Repository quintoandar/butterfree, pull requests merged in 2020-08, with the labels that each got.

#224 Change workflow.
  .github/workflows/publish.yml
  WORKFLOW.md
Labels: bug

#220 [MLOP-440] Python 3.7 bump and Fixing Dependencies
  .github/workflows/publish.yml
  .github/workflows/test.yml
  CONTRIBUTING.md
  Makefile
  README.md
  docs/requirements.txt
  docs/source/getstart.md
  requirements.dev.txt
  requirements.lint.txt
  requirements.txt
  setup.py
Labels: bug

#225 Fix container name in Workflow
  .github/workflows/publish.yml
Labels: bug

#219 [MLOP-427] Add status badges
  README.md
Labels: documentation, enhancement

#221 [MLOP-398] Pipeline run method will receive an optional start_date argument #212
  butterfree/extract/source.py
  butterfree/pipelines/feature_set_pipeline.py
  butterfree/transform/aggregated_feature_set.py
  butterfree/transform/feature_set.py
  tests/unit/butterfree/pipelines/test_feature_set_pipeline.py
  tests/unit/butterfree/transform/test_aggregated_feature_set.py
  tests/unit/butterfree/transform/test_feature_set.py
Labels: enhancement

#222 [MLOP-399] Source date boundaries must be changed
  butterfree/constants/window_definitions.py
  butterfree/transform/aggregated_feature_set.py
  butterfree/transform/utils/window_spec.py
  tests/unit/butterfree/transform/test_aggregated_feature_set.py
Labels: enhancement

#226 Release 1.0.2
  CHANGELOG.md
  setup.py
Labels: release

#227 [FIX] Downgrade Python Version in Pyenv
  Makefile
Labels: bug

#229 Fix docs.
  docs/requirements.txt
  docs/source/conf.py
Labels: bug

#230 Fix Docs - Add more dependencies
  docs/requirements.txt
Labels: bug

#231 [MLOP-401] Define date boundaries within the scope of the writing operation
  butterfree/dataframe_service/__init__.py
  butterfree/dataframe_service/incremental_strategy.py
  butterfree/extract/readers/__init__.py
  butterfree/extract/readers/reader.py
  butterfree/pipelines/feature_set_pipeline.py
  butterfree/transform/aggregated_feature_set.py
  butterfree/transform/feature_set.py
  tests/integration/butterfree/transform/conftest.py
  tests/integration/butterfree/transform/test_aggregated_feature_set.py
  tests/unit/butterfree/dataframe_service/test_incremental_strategy.py
  tests/unit/butterfree/extract/readers/test_reader.py
Labels: enhancement

#233 [MLOP-455] Spark Table Schema Compatibility Hook
  butterfree/hooks/__init__.py
  butterfree/hooks/hook.py
  butterfree/hooks/schema_compatibility/__init__.py
  butterfree/hooks/schema_compatibility/spark_table_schema_compatibility_hook.py
  tests/unit/butterfree/hooks/__init__.py
  tests/unit/butterfree/hooks/schema_compatibility/__init__.py
  tests/unit/butterfree/hooks/schema_compatibility/test_spark_table_schema_compatibility_hook.py
Labels: feature

#235 [MLOP-436] Deal with execution_date parameter
  butterfree/dataframe_service/incremental_strategy.py
  butterfree/extract/source.py
  butterfree/pipelines/feature_set_pipeline.py
  tests/integration/butterfree/pipelines/conftest.py
  tests/integration/butterfree/pipelines/test_feature_set_pipeline.py
  tests/unit/butterfree/dataframe_service/test_incremental_strategy.py
Labels: enhancement

#237 [MLOP-459] Create HookableComponent
  butterfree/hooks/__init__.py
  butterfree/hooks/hookable_component.py
  tests/unit/butterfree/hooks/test_hookable_component.py
Labels: feature

#239 [MLOP-454] Create Cassandra Check Hook
  butterfree/hooks/schema_compatibility/__init__.py
  butterfree/hooks/schema_compatibility/cassandra_table_schema_compatibility_hook.py
  tests/unit/butterfree/hooks/schema_compatibility/test_cassandra_table_schema_compatibility_hook.py
Labels: enhancement
