Repository quintoandar/butterfree, pull requests merged in 2021-02, with the labels that each got.

#283 [BUG] Fix Staging GithubActions Pipeline
  .github/workflows/staging.yml
Labels: bug

#285 [BUG] Fix Staging GithubActions Pipeline
  .github/workflows/staging.yml
Labels: bug

#286 [BUG] Change version on setup.py to PyPI
  .github/workflows/staging.yml
  Makefile
Labels: bug

#284 Keep milliseconds when using 'from_ms' argument in timestamp feature
  butterfree/transform/features/timestamp_feature.py
  tests/unit/butterfree/transform/features/conftest.py
  tests/unit/butterfree/transform/features/test_timestamp_feature.py
Labels: bug

#287 Change trigger for pipeline staging
  .github/workflows/staging.yml
Labels: bug

#288 Create a dev package
  CHANGELOG.md
  setup.py
Labels: pre-release

#281 [MLOP-633] Butterfree dev workflow, update documentation
  README.md
  WORKFLOW.md
Labels: documentation

#279 [MLOP-632] Butterfree dev workflow, automate release description
  .github/workflows/publish.yml
Labels: feature

#282 [MLOP-636] Create migration classes
  butterfree/migrations/__init__.py
  butterfree/migrations/cassandra_migration.py
  butterfree/migrations/metastore_migration.py
  butterfree/migrations/migration.py
Labels: feature

#278 [MLOP-635] Rebase Incremental Job/Interval Run branch for test on selected feature sets
  .gitignore
  CHANGELOG.md
  butterfree/clients/cassandra_client.py
  butterfree/clients/spark_client.py
  butterfree/configs/db/metastore_config.py
  butterfree/configs/environment.py
  butterfree/constants/window_definitions.py
  butterfree/dataframe_service/__init__.py
  butterfree/dataframe_service/incremental_strategy.py
  butterfree/dataframe_service/partitioning.py
  butterfree/extract/readers/file_reader.py
  butterfree/extract/readers/reader.py
  butterfree/extract/source.py
  butterfree/hooks/__init__.py
  butterfree/hooks/hook.py
  butterfree/hooks/hookable_component.py
  butterfree/hooks/schema_compatibility/__init__.py
  butterfree/hooks/schema_compatibility/cassandra_table_schema_compatibility_hook.py
  butterfree/hooks/schema_compatibility/spark_table_schema_compatibility_hook.py
  butterfree/load/sink.py
  butterfree/load/writers/historical_feature_store_writer.py
  butterfree/load/writers/online_feature_store_writer.py
  butterfree/load/writers/writer.py
  butterfree/pipelines/feature_set_pipeline.py
  butterfree/transform/aggregated_feature_set.py
  butterfree/transform/feature_set.py
  butterfree/transform/utils/window_spec.py
  examples/interval_runs/interval_runs.ipynb
  setup.py
  tests/integration/butterfree/load/test_sink.py
  tests/integration/butterfree/pipelines/conftest.py
  tests/integration/butterfree/pipelines/test_feature_set_pipeline.py
  tests/integration/butterfree/transform/conftest.py
  tests/integration/butterfree/transform/test_aggregated_feature_set.py
  tests/integration/butterfree/transform/test_feature_set.py
  tests/unit/butterfree/clients/conftest.py
  tests/unit/butterfree/clients/test_cassandra_client.py
  tests/unit/butterfree/clients/test_spark_client.py
  tests/unit/butterfree/dataframe_service/conftest.py
  tests/unit/butterfree/dataframe_service/test_incremental_srategy.py
  tests/unit/butterfree/dataframe_service/test_partitioning.py
  tests/unit/butterfree/extract/conftest.py
  tests/unit/butterfree/extract/readers/test_file_reader.py
  tests/unit/butterfree/extract/readers/test_reader.py
  tests/unit/butterfree/hooks/__init__.py
  tests/unit/butterfree/hooks/schema_compatibility/__init__.py
  tests/unit/butterfree/hooks/schema_compatibility/test_cassandra_table_schema_compatibility_hook.py
  tests/unit/butterfree/hooks/schema_compatibility/test_spark_table_schema_compatibility_hook.py
  tests/unit/butterfree/hooks/test_hookable_component.py
  tests/unit/butterfree/load/conftest.py
  tests/unit/butterfree/load/test_sink.py
  tests/unit/butterfree/load/writers/test_historical_feature_store_writer.py
  tests/unit/butterfree/load/writers/test_online_feature_store_writer.py
  tests/unit/butterfree/pipelines/conftest.py
  tests/unit/butterfree/pipelines/test_feature_set_pipeline.py
  tests/unit/butterfree/transform/conftest.py
  tests/unit/butterfree/transform/test_aggregated_feature_set.py
  tests/unit/butterfree/transform/test_feature_set.py
Labels: enhancement

#293 Allow slide selection
  Makefile
  butterfree/transform/aggregated_feature_set.py
  butterfree/transform/utils/window_spec.py
  setup.py
  tests/unit/butterfree/transform/conftest.py
  tests/unit/butterfree/transform/test_aggregated_feature_set.py
Labels: feature, question

#295 Fix Slide Duration Typo
  butterfree/transform/aggregated_feature_set.py
  setup.py
  tests/unit/butterfree/transform/conftest.py
  tests/unit/butterfree/transform/test_aggregated_feature_set.py
Labels: bug
