Repository quintoandar/butterfree, pull requests merged in 2021-04, with the labels that each got.

#305 [FIX] Add Partition types for Metastore
  butterfree/migrations/database_migration/metastore_migration.py
  tests/unit/butterfree/migrations/database_migration/test_metastore_migration.py
Labels: bug

#307 [BUG] Change logging config
  Makefile
  butterfree/__init__.py
  butterfree/_cli/migrate.py
  butterfree/configs/logger.py
  butterfree/logging.conf
  butterfree/migrations/database_migration/database_migration.py
  logs/logging.json
  setup.py
  tests/unit/butterfree/_cli/test_migrate.py
Labels: bug

#308 Change solution for tracking logs
  butterfree/_cli/migrate.py
  requirements.txt
  setup.py
Labels: feature

#309 Read and write consistency level options
  butterfree/clients/cassandra_client.py
  butterfree/configs/db/cassandra_config.py
  butterfree/configs/environment.py
  tests/unit/butterfree/configs/db/test_cassandra_config.py
Labels: enhancement

#310 [BUG] Fix KafkaReader
  butterfree/extract/readers/kafka_reader.py
  setup.py
  tests/unit/butterfree/extract/readers/test_kafka_reader.py
Labels: bug

#311 [BUG] Fix SparkClient read method
  butterfree/clients/spark_client.py
  setup.py
  tests/unit/butterfree/clients/test_spark_client.py
Labels: bug

#313 Remove metastore migrate
  butterfree/_cli/migrate.py
  butterfree/clients/abstract_client.py
  butterfree/clients/cassandra_client.py
  butterfree/clients/spark_client.py
  butterfree/load/writers/online_feature_store_writer.py
  butterfree/migrations/database_migration/database_migration.py
  setup.py
  tests/unit/butterfree/_cli/test_migrate.py
Labels: feature

#315 Fix link in Buttefree Doc
  docs/source/extract.md
Labels: documentation

#316 [BUG] Fix Cassandra Connect Session
  butterfree/clients/cassandra_client.py
  setup.py
  tests/unit/butterfree/clients/test_cassandra_client.py
Labels: bug

#318 [BUG] Fix migration query
  butterfree/migrations/database_migration/cassandra_migration.py
  butterfree/migrations/database_migration/database_migration.py
  butterfree/migrations/database_migration/metastore_migration.py
  setup.py
  tests/unit/butterfree/migrations/database_migration/test_cassandra_migration.py
  tests/unit/butterfree/migrations/database_migration/test_metastore_migration.py
Labels: bug

#319 Fix migration query: Add K_TYPE.
  butterfree/migrations/database_migration/cassandra_migration.py
  setup.py
  tests/unit/butterfree/migrations/database_migration/test_cassandra_migration.py
Labels: bug
