Repository quintoandar/butterfree, pull requests merged in 2021-06, with the labels that each got.

#325 [MLOP-727] Improve logging messages
  butterfree/_cli/migrate.py
Labels: feature

#324 [MLOP-728] Improve logging messages
  butterfree/migrations/database_migration/database_migration.py
Labels: feature

#326 [MLOP-729][BUG] Fix method to generate agg feature name
  butterfree/transform/transformations/aggregated_transform.py
  setup.py
Labels: bug

#327 [MLOP-691] Include step to add partition to SparkMetastore during writing of Butterfree
  butterfree/load/writers/historical_feature_store_writer.py
  setup.py
  tests/unit/butterfree/load/writers/test_historical_feature_store_writer.py
Labels: bug, feature

#330 Add the missing link for H3 geohash
  examples/simple_feature_set/simple_feature_set.ipynb
  examples/spark_function_and_window/spark_function_and_window.ipynb
Labels: bug
