Repository quintoandar/butterfree, pull requests merged in 2021-03, with the labels that each got.

#292 [MLOP-637] Implement diff method
  butterfree/migrations/__init__.py
  butterfree/migrations/cassandra_migration.py
  butterfree/migrations/database_migration/__init__.py
  butterfree/migrations/database_migration/cassandra_migration.py
  butterfree/migrations/database_migration/database_migration.py
  butterfree/migrations/database_migration/metastore_migration.py
  butterfree/migrations/metastore_migration.py
  butterfree/migrations/migrate.py
  butterfree/migrations/migration.py
  setup.cfg
  tests/unit/butterfree/migrations/__init__.py
  tests/unit/butterfree/migrations/database_migration/__init__.py
  tests/unit/butterfree/migrations/database_migration/conftest.py
  tests/unit/butterfree/migrations/database_migration/test_database_migration.py
Labels: enhancement

#298 [MLOP-640] Create CLI with migrate command
  butterfree/_cli/__init__.py
  butterfree/_cli/main.py
  butterfree/_cli/migrate.py
  requirements.txt
  setup.py
  tests/mocks/__init__.py
  tests/mocks/entities/__init__.py
  tests/mocks/entities/first/__init__.py
  tests/mocks/entities/first/first_pipeline.py
  tests/mocks/entities/second/__init__.py
  tests/mocks/entities/second/deeper/__init__.py
  tests/mocks/entities/second/deeper/second_pipeline.py
  tests/unit/butterfree/_cli/__init__.py
  tests/unit/butterfree/_cli/test_migrate.py
Labels: feature

#291 [MLOP-645] Implement query method, cassandra
  butterfree/migrations/database_migration/cassandra_migration.py
  butterfree/migrations/database_migration/database_migration.py
  butterfree/migrations/database_migration/metastore_migration.py
  tests/unit/butterfree/migrations/database_migration/conftest.py
  tests/unit/butterfree/migrations/database_migration/test_cassandra_migration.py
  tests/unit/butterfree/migrations/database_migration/test_database_migration.py
Labels: feature

#301 [MLOP-671] Implement get_schema on Spark client
  butterfree/clients/spark_client.py
  tests/unit/butterfree/clients/test_spark_client.py
Labels: feature

#294 [MLOP-648] Implement query method, metastore
  butterfree/constants/migrations.py
  butterfree/migrations/database_migration/cassandra_migration.py
  butterfree/migrations/database_migration/database_migration.py
  butterfree/migrations/database_migration/metastore_migration.py
  tests/unit/butterfree/migrations/database_migration/test_metastore_migration.py
Labels: feature

#302 Fix Validation Step
  butterfree/configs/db/metastore_config.py
  butterfree/load/writers/historical_feature_store_writer.py
  butterfree/load/writers/online_feature_store_writer.py
  setup.py
  tests/integration/butterfree/load/test_sink.py
  tests/integration/butterfree/pipelines/test_feature_set_pipeline.py
  tests/unit/butterfree/load/test_sink.py
  tests/unit/butterfree/load/writers/test_historical_feature_store_writer.py
  tests/unit/butterfree/load/writers/test_online_feature_store_writer.py
Labels: bug

#300 [MLOP-647] [MLOP-646] Apply migrations
  butterfree/_cli/migrate.py
  butterfree/configs/db/abstract_config.py
  butterfree/configs/db/cassandra_config.py
  butterfree/configs/db/kafka_config.py
  butterfree/configs/db/metastore_config.py
  butterfree/load/writers/historical_feature_store_writer.py
  butterfree/load/writers/online_feature_store_writer.py
  butterfree/load/writers/writer.py
  butterfree/migrations/__init__.py
  butterfree/migrations/database_migration/__init__.py
  butterfree/migrations/database_migration/cassandra_migration.py
  butterfree/migrations/database_migration/database_migration.py
  butterfree/migrations/database_migration/metastore_migration.py
  butterfree/migrations/migrate.py
  tests/unit/butterfree/_cli/test_migrate.py
  tests/unit/butterfree/migrations/database_migration/conftest.py
  tests/unit/butterfree/migrations/database_migration/test_database_migration.py
Labels: enhancement

#303 [BUG] Apply create_partitions to historical validate
  butterfree/load/writers/historical_feature_store_writer.py
  setup.py
Labels: bug
